name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: git -C "E:\siteB" pull origin main
        shell: powershell

      - name: Build or migrate
        run: |
          echo "Run build or collectstatic if needed"
        shell: powershell

      - name: Restart IIS site
        run: |
          & "C:\Windows\System32\inetsrv\appcmd.exe" stop site "site-b"
          Start-Sleep -Seconds 2
          & "C:\Windows\System32\inetsrv\appcmd.exe" start site "site-b"
        shell: powershell
