name: Auto Pull and Restart Specific IIS Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Latest Code
        run: git -C "E:\test\react\react" pull origin main
      - name: Restart IIS Site via appcmd
        run: |
          & "C:\Windows\System32\inetsrv\appcmd.exe" stop site "voice"
          Start-Sleep -Seconds 2
          & "C:\Windows\System32\inetsrv\appcmd.exe" start site "voice"
        shell: powershell
