name: Auto Pull and Restart Specific IIS Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          $LogPath = "C:/logs/repo-name"
          if (!(Test-Path $LogPath)) { New-Item -ItemType Directory -Path $LogPath }
          $LogFile = "$LogPath/deploy.log"
          Add-Content -Path $LogFile -Value "`n===== Pulling latest code - $(Get-Date) ====="
          git -C "E:\test\react\react" pull origin main
          Add-Content -Path $LogFile -Value "===== Pulling latest code completed - $(Get-Date) ====="
          
          # Create archive directory if it doesn't exist
          $ArchivePath = "E:\test\react\archive"
          if (!(Test-Path $ArchivePath)) { New-Item -ItemType Directory -Path $ArchivePath }
          
          # Archive old build with timestamp
          $Timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
          $ArchiveFolder = "$ArchivePath\build_$Timestamp"
          Add-Content -Path $LogFile -Value "===== Archiving old build to $ArchiveFolder - $(Get-Date) ====="
          
          # Check if build directory exists before copying
          $BuildPath = "E:\test\react\react\build"
          if (Test-Path $BuildPath) {
            Copy-Item -Path $BuildPath -Destination $ArchiveFolder -Recurse
            Add-Content -Path $LogFile -Value "===== Old build archived successfully - $(Get-Date) ====="
          } else {
            Add-Content -Path $LogFile -Value "===== No previous build found to archive - $(Get-Date) ====="
          }
          
          Add-Content -Path $LogFile -Value "===== Starting build process - $(Get-Date) ====="
          cd "E:\test\react\react"
          npm run build
          Add-Content -Path $LogFile -Value "===== Build process completed - $(Get-Date) ====="

          Add-Content -Path $LogFile -Value "===== Stopping Server - $(Get-Date) ====="
          & "C:\Windows\System32\inetsrv\appcmd.exe" stop site "voice" 2>&1 | Tee-Object -FilePath $LogFile -Append
          Start-Sleep -Seconds 2
          Add-Content -Path $LogFile -Value "===== Starting Server - $(Get-Date) ====="
          & "C:\Windows\System32\inetsrv\appcmd.exe" start site "voice" 2>&1 | Tee-Object -FilePath $LogFile -Append
        shell: powershell
